### ISSUE TITLE
Migration error running backend tests

### ISSUE THREAD

**Issue by wilsonianb** [coilhq/rafiki#36]
I get the following when running `yarn test` or `yarn workspace backend test` locally on `main`:

```
Determining test suites to run...migration file "20210422134422_create_events_table.js" failed
migration failed with error: create table "events" ("id" uuid not null, "name" varchar(255) not null, "type" varchar(255) not null, "typeId" varchar(255) not null, "payload" jsonb not null, "createdAt" timestamptz default CURRENT_TIMESTAMP, "updatedAt" timestamptz default CURRENT_TIMESTAMP) - relation "events" already exists
error: create table "events" ("id" uuid not null, "name" varchar(255) not null, "type" varchar(255) not null, "typeId" varchar(255) not null, "payload" jsonb not null, "createdAt" timestamptz default CURRENT_TIMESTAMP, "updatedAt" timestamptz default CURRENT_TIMESTAMP) - relation "events" already exists
    at Parser.parseErrorMessage (/home/brandon/raio/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-270e72d38a.zip/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/brandon/raio/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-270e72d38a.zip/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/brandon/raio/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-270e72d38a.zip/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/brandon/raio/.yarn/cache/pg-protocol-npm-1.5.0-390f8d9ed8-270e72d38a.zip/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:376:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)
```

`knex rollback` says `Already at the base migration`

**Comment by wilsonianb** [comment]
Can no longer reproduce.
